Adds IceStrength to RulesClassExtension and IceDestructionEnabled scenario option. #897
Vinifera-Developers/Vinifera pull request #932
Opened 2022-12-02 22:59 UTC by Rampastring

Closes #897 

This PR adds two keys for customizing ice destruction logic.

1)

On a scenario file,

```ini
[Basic]
IceDesctructionEnabled=<bool> ; determines whether ice tiles can be destroyed in the scenario. Defaults to yes.
```

2) 

In rules,

```ini
[CombatDamage]
IceStrength=<int> ; Defines the strength of ice. Higher values make ice less likely to
                              ; break from a shot. 0 makes ice break from any shot, like in the original game.
```

2023-02-14 00:20 UTC, CCHyper requested changes

2023-02-14 00:20 UTC, CCHyper commented on src/extensions/combat/combatext_hooks.cpp
> +    GET_REGISTER_STATIC(const WarheadTypeClass*, warhead, edi);
Needs a space between `WarheadTypeClass` and `*`.

This is most likely your MSVC auto-formatting taking over here, you can change those easily in Tools -> Options -> Text Editor -> C/C++.

2023-02-14 00:20 UTC, CCHyper commented on src/extensions/combat/combatext_hooks.cpp
> +        if (RuleExtension->IceStrength <= 0 || Scen->RandomNumber(0, RuleExtension->IceStrength) < strength) {
Use `Random_Pick` here (`tibsun_inlines.h`).

2023-02-14 00:20 UTC, CCHyper commented on src/extensions/scenario/scenarioext_functions.cpp
> +void Read_Scenario_Read_Basic_Section_Options(CCINIClass &scenario_ini)
This patch is not required. Rebase this branch to the upstream develop and add the INI reading line to `ScenarioClassExtension::Read_INI`.

2023-03-16 09:17 UTC, Rampastring commented
@CCHyper Updated.

2023-03-16 14:21 UTC, CCHyper requested changes

2023-03-16 14:21 UTC, CCHyper commented on src/extensions/combat/combatext_hooks.cpp
> +        if (RuleExtension->IceStrength <= 0 || Random_Pick(0, RuleExtension->IceStrength) < strength) {
Can you check the output assembly for this in Release builds please? `Random_Pick` is an inline function and its possible the compiler might inline it using a different register than the expected `EAX` and `ECX` here.

2023-03-16 14:21 UTC, CCHyper commented on src/extensions/scenario/scenarioext.cpp
>  void ScenarioClassExtension::Compute_CRC(WWCRCEngine &crc) const
The `ScenarioClassExtension` constructor is missing initialisation of `IsIceDestruction`, which I assume should be set to `true`.

2023-03-16 14:21 UTC, CCHyper commented on src/extensions/scenario/scenarioext.cpp
> +    const char* const BASIC = "Basic";
This should be static, so;
`static const char * const BASIC = "Basic";` _(not the formatting of the `*` again)_.
Also, add a blank line between its definition and the INI operation please.

2023-03-16 14:24 UTC, Rampastring commented on src/extensions/scenario/scenarioext.cpp
>  void ScenarioClassExtension::Compute_CRC(WWCRCEngine &crc) const
The constructor calls `Init_Clear` which sets `IsIceDestruction` to `true`.

2023-03-16 14:28 UTC, Rampastring commented on src/extensions/combat/combatext_hooks.cpp
> +        if (RuleExtension->IceStrength <= 0 || Random_Pick(0, RuleExtension->IceStrength) < strength) {
Downloaded the artifact from the bot comment and checked. Seems there's a function call after all, and the compiler used `edx`. Which should also be fine as `edx` is written to before read next time. Or does the bot generate a debug build?

```x86asm
.text:10010EAC loc_10010EAC:                           ; CODE XREF: _Explosion_Damage_IsIceDestruction_Patch+2Cj
.text:10010EAC                 mov     eax, RuleExtension
.text:10010EB1                 cmp     dword ptr [eax+0Ch], 0
.text:10010EB5                 jle     short loc_10010ECE
.text:10010EB7                 mov     eax, RuleExtension
.text:10010EBC                 mov     edx, [eax+0Ch]
.text:10010EBF                 xor     ecx, ecx
.text:10010EC1                 call    Random_Pick_int_
.text:10010EC6                 cmp     eax, dword_101031BC
.text:10010ECC                 jge     short loc_10010ED0
```

`Random_Pick_int_` is
```x86asm
.text:1000CDE0 Random_Pick_int_ proc near
.text:1000CDE0                 mov     eax, Scen
.text:1000CDE5                 push    edx
.text:1000CDE6                 push    ecx
.text:1000CDE7                 mov     ecx, [eax]
.text:1000CDE9                 add     ecx, 218h
.text:1000CDEF                 call    Random2Class__operator__
.text:1000CDF4                 retn
.text:1000CDF4 Random_Pick_int_ endp
```

2023-03-16 14:36 UTC, CCHyper commented on src/extensions/scenario/scenarioext.cpp
>  void ScenarioClassExtension::Compute_CRC(WWCRCEngine &crc) const
The class constructor should always initialise its members, regardless of the calls it makes within the body of the constructor. In this case, `Init_Clear` is fine to set this to true as it can be called at any time.

2023-03-16 14:36 UTC, CCHyper commented on src/extensions/combat/combatext_hooks.cpp
> +        if (RuleExtension->IceStrength <= 0 || Random_Pick(0, RuleExtension->IceStrength) < strength) {
Ok, that's great. We should be fine then 👍.

2023-03-16 14:43 UTC, Rampastring commented on src/extensions/scenario/scenarioext.cpp
> +    const char* const BASIC = "Basic";
Wonder if you could add an editor config file to the project that tells VS which formatting settings to use.

2023-03-29 21:06 UTC, merged